### ISSUE TITLE
Would this work on a M83 Tiny?

### ISSUE THREAD

**Issue by uberfunk** [UHDbits/M73-Tiny-OpenCore#14] opened 2023-03-23 22:12 UTC
Which do you have: an M73 Tiny or an M93p?:
Neither, M83 Tiny.

Do your specifications match the ones shown in the README.md? (not including the USB WiFi adapter):
Very close...

If your specifications do not match, what are your specifications?:
Intel Core i5-4590T @ 2.00Ghz
2x4GB (8GB) of DDR3-1600
Intel HD Graphics 4600
256GB SSD
Intel I217-LM
[Full M83 Tiny specs](https://download.lenovo.com/parts/ThinkCentre/m83_tiny_overview.pdf)

What version of OS X/macOS are you using?:
I am planning on installing Monterey. 

What is your issue?:
As the title says, would this work on a M83 Tiny? Specs are similar and it's from the same era as the M73 and M93 so I don't see why this wouldn't work. But can you see any "gotchas" I might run into (other than the wifi not working and no VGA)? Thanks!

**Comment by UHDbits** [comment] 2023-03-24 17:35
Huh, I never knew that existed! According to the specs, I see no reason why
this configuration wouldn't work on this computer. The only other "gotcha"
I can think of is some bugs with Ventura, unless you aren't planning to use
Ventura on the machine. Most of the bugs are pretty minor though, so it's
not a major issue. I recommended double checking the issues listed to make
sure there is nothing that should affect you, there should be no extra
issues caused by the M83.

If you do test this, I would greatly appreciate it if you let me know if it
works! Thank you!

**Comment by UHDbits** [comment] 2023-03-24 17:35
Sorry, just noticed it said you are planning to install Monterey, so the
Ventura issues don't apply.

**Comment by humblepi4** [comment] 2023-04-13 04:35
I have been trying to get Monterey working on my M83 TFF and I'm having issues.

cpu: i5-4570T device id 12040000 (0x412)
igpu: HD4600
wifi: AzureWave AW-CE123H (BCM94352HMB)
256 SSD
2x8GB DDR3

I've tried using your efi but get all kinds of errors when throwing your SSDTs for the 4 core i7 at my 2 core i5.
I've tried creating my own SSDTs with SSDTTime in windows but the system bootloops before I can see whats happening. 
I've spent hours on it and it's late so I will try and get some better debug info tomorrow.
I've tried the prebuilt SSDTs and haven't reached the installer that way either.
One major problem is that I'm using VGA and/or a passive DP to HDMI adapter. 
I don't own a display with a DP. 
What's interesting is that I've had success with both VGA and DP working (on Monterey) with this machine when using orillia images/efi and designating all three ports as DP among some other settings under DeviceProperties. I just could not get hardware acceleration to work which is why I'm looking for a more authentic approach. In the meantime I have ordered a VGA to HDMI active adapter and will be testing that out soon. I like the work here at this repo. Any input on things I could try would be great and I'll be back with better debug info.

Here's my DeviceProperties settings for display - these should work for anyone with a matching a platform id (0300220D) and 3 ports:

![Screenshot 2023-04-13 at 12 29 18 AM](https://user-images.githubusercontent.com/124759710/231654445-9815565d-b584-4d27-ad93-cecd42f4a2de.png)

**Comment by UHDbits** [comment] 2023-04-13 17:20
Thanks a ton for all the information! I never did think about the SSDTs being different between the M73 and M83 Tiny, and since I built my SSDTs using SSDTTime for my computer, I guess they don't work for others. I'll think about replacing tehm with the prebuilts, just to make this config more compatible, but I also like to make the configurations as lightweight as possible.

By the way, SSDT-USBX is actually required for Skylake SMBIOS, not just Skylake machines. That's why I added it because I'm using a Kaby Lake SMBIOS for Ventura support, so that's why it's there. 
Do you know if the USBMap worked with native kexts, or did you just test it with the two kexts? Again, I just used the singular kext because they seemed lighter weight, since it was using the native USB properties. But, this also causes the USB maps to be SMBIOS specific, which is why you need to enter the SMBIOS that you are using in the USBToolbox application.

Also, thanks for the info on getting VGA working! I'll check to see if that works here (with graphics acceleration), and if it does I'll add those settings to the configuration. 

I'll try to check out your OpenCore logs as soon as possible, hopefully by the end of today. I just kind of quickly looked over your comments to respond to them, so sorry for any mistakes made in this comment. I'll look at all of this closer later. Thanks a ton once again!

**Comment by UHDbits** [comment] 2023-04-13 17:23
Also, could you try adding these boot arguments to the config? These should hopefully stop the computer from rebooting when it crashes, and will allow you to take photos of the macOS verbose logs.

"-v debug=0x100 keepsyms=1" Make sure to add them without the "s

**Comment by humblepi4** [comment] 2023-04-13 18:04
Ok thanks!
I'm going to start again with your efi and leave things like the ssdt-usbx.
I will toy around with different usb scenarios and report back. I havnt got far enough to know if they're working but I could do some testing on the "fast and easy" installation.
I will set the boot args as you suggested.
side note:
in the image above the "dpcd-max-link-rate" designation of 14 is for 4k output. again more info under the spoiler at whatevergreen.

**Comment by UHDbits** [comment] 2023-04-13 18:46
Yeah I know that (I'm currently working on an OC config for a 4K laptop),
but 4K60 already seems to work on this config, at least for the M73 Tiny,
because I'm using a 4K60 monitor with it right now. Does it not work for
you without that?

**Comment by humblepi4** [comment] 2023-04-13 19:06
Not sure. Just tried to throw everything I could at the VGA to make it appear as Display Port because I read somewhere that some motherboards assign a display port designation to the VGA and thought I might get lucky. Something is allowing to work on the "fast and easy" install. I know he is using the RestrictEvents.kext and maybe that has something to do with it. It remains to be seen if I can get acceleration working through VGA. I've read that VGA doesn't work at all with macOS and so far that is not true with this setup.

**Comment by humblepi4** [comment] 2023-04-13 20:13
OK. No reboots but still can't get to installer.

I re-downloaded your efi.
replaced your SSDTs with my SSDTs including the USBX - built them with ssdttime
I added my usbmap.kext and the usbtoolbox.kext (documentation says to add this kext too) - used native setting and imac18,1
added boot args and debug settings in misc
reloaded the plist
That's it
The boot hangs

[opencore-2023-04-13-194800.txt](https://github.com/UHDbits/M73-Tiny-OpenCore/files/11226078/opencore-2023-04-13-194800.txt)
 
If you want I can get system report dump too.

I noticed something strange when building the SSDTs ("Not Valid EC Device")

![Screen Shot 2023-04-13 at 2 45 20 PM](https://user-images.githubusercontent.com/124759710/231872520-f3b34e6a-0ca5-4c3c-a986-e140ec55010a.png)

**Comment by UHDbits** [comment] 2023-04-13 20:15
Also it would be great if you could get the system report dump, or just send an image at the end of the verbose messages.

**Comment by humblepi4** [comment] 2023-04-13 20:20
Are you trying to run 4K through a VGA port?
no I left your settings 

![IMG_20230413_152636_364](https://user-images.githubusercontent.com/124759710/231873929-34ad2898-ead3-4710-9e51-007bad070ecb.jpg)

**Comment by UHDbits** [comment] 2023-04-13 20:21
Mhm, that's definitely an issue with the GPU not being initialized properly,  because that "gIOScreenLockState" message basically means that booting has basically finished, and it's initializing the GPU. Have you been able to test it out of anything other than the VGA port?

**Comment by humblepi4** [comment] 2023-04-13 20:32
Getting the DP to HDMI adapter to display is tricky and random. 
I ran again with VGA and the DeviceProperties settings from before and got something a bit different:

![IMG_20230413_152636_364](https://user-images.githubusercontent.com/124759710/231876367-d4e71f06-1697-4543-a4fa-99ec8c582afc.jpg)

**Comment by UHDbits** [comment] 2023-04-13 20:35
It's still ending up being the same thing in that case, with "IOG flags 0x3 (0x51)" meaning a similar thing to what was mentioned above.

**Comment by humblepi4** [comment] 2023-04-13 20:42
It's hard to read but I will get a pic of the -v through the adapter and edit this comment

**Comment by humblepi4** [comment] 2023-04-13 22:22
I guess I need to get a display with DP ports

**Comment by UHDbits** [comment] 2023-04-13 23:11
OpenCore Legacy Patcher doesn't need to be used on Monterey, only on
Ventura. Plus, that function doesn't work on hackintoshes, all you need to
do it "post-install patches"

**Comment by UHDbits** [comment] 2023-04-18 20:04
Okay, so I think in the README.md I may just suggest using prebuilt SSDTs for the M83 and M93p? I'd prefer to keep the configuration itself as lightweight as possible, so I will just provide links to the prebuilt SSDTs and replace them. But, of course, I'm not exactly sure if this would completely finish the problem. I may also just put in known issues that it's possible that the M83 Tiny and M93p may not work with the configuration, and suggest using the configuration as a guide (which is the point of the config anyways), and make your own. I'll think about which one I will do.

**Comment by UHDbits** [comment] 2023-04-25 18:18
@humblepi4, just a quite question, what version of macOS are you attempting to boot? I understand that it seems like you will need a DP display anyways (which is quite strange, I've used a DP to DVI adapter before and it's worked just fine), but I have just seen the kernel panic that you sent above and am trying to see the cause of it.
If you are using Big Sur or older, please note that the latest version of the configuration does not support Big Sur. I think this may be causing your issues, but it's also quite possible that I am wrong.

**Comment by UHDbits** [comment] 2023-04-27 15:05
Yeah, no problem! I'm going to do some research to try to fix the kernel
panic you had with the DP adapter.

**Comment by humblepi4** [comment] 2023-04-27 16:11
Right now I'm using VGA to HDMI adapter.
I copied your EFI and replaced the SSDTs with my own and generated a new SMBIOS (iMac18,1)
Currently installing Ventura.
*couldn't get display through the DP adapter - I will try again if I get through the install

**Comment by humblepi4** [comment] 2023-04-27 17:07
I have successfully installed ventura now when I try to do root patching with OCLP it's telling me that SIP is enabled. I tried disabling it in plist and also with the toggle sip option but I still get the same message from OCLP. Any ideas?

**Comment by UHDbits** [comment] 2023-04-27 18:32
Thanks for the info, nice to know that it looks like replacing the SSDTs in the config at least partially fixes M83 Tiny support. I'll make sure to add that information to the repository soon. Also, were you able to get the VGA output working? Not sure if you did anything to fix it, but let me know if you did.

After root patching does it boot loop or just kind of freeze?

**Comment by humblepi4** [comment] 2023-04-27 23:57
> Thanks for the info, nice to know that it looks like replacing the SSDTs in the config at least partially fixes M83 Tiny support. I'll make sure to add that information to the repository soon. Also, were you able to get the VGA output working? Not sure if you did anything to fix it, but let me know if you did.
> 
> After root patching does it boot loop or just kind of freeze?

I built the same three SSDTs that are present in your ACPI folder using SSDTTime in windows and replaced the originals with the ones for m83 with i5-4570T. Opencore menu and installation worked through the VGA to HDMI adapter and I was able to boot to ventura desktop but no hardware acceleration (as expected) after running the OCLP root patch it froze during boot sequence - no bootloop. I will fire it up with debug settings and see if I can get any info.

**Comment by humblepi4** [comment] 2023-04-28 00:41
It looks to me like maybe it's the VGA issue again.
When I power the machine up with the DP to HDMI the display will show the lenovo splash then the 1st boot sequence text before the OC menu then I lose display. Same thing happens with windows.
![IMG_20230427_202158_229](https://user-images.githubusercontent.com/124759710/235025475-53e254fa-e811-4a02-b777-08c704aa0d59.jpg)

**Comment by UHDbits** [comment] 2023-04-28 18:07
Mhn, that's interesting, maybe activating graphics acceleration causes VGA to stop working? With the DisplayPort adapter, are you able to see the OC menu at all? Or does it freeze before the boot options even show up?

**Comment by humblepi4** [comment] 2023-04-30 19:24
> Mhn, that's interesting, maybe activating graphics acceleration causes VGA to stop working? With the DisplayPort adapter, are you able to see the OC menu at all? Or does it freeze before the boot options even show up?

The above screenshot was after root patch through VGA adapter. With the Display Port adapter I can  see OC menu then display goes black and looses signal. The same with windows the pre desktop screen shows then looses signal. As if the computer is switching the port off.

**Comment by uberfunk** [comment] 2023-05-12 18:56
@UHDbits Did you ever have an issue with shutting down? In particular, this issue: https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html

I can't seem to resolve it. Restart and Sleep work fine but Shutdown not actually shutting down is driving me nuts!

**Comment by UHDbits** [comment] 2023-05-12 20:26
@humblepi4 Mhm, I really wish I could help more, but I'm not sure anymore if this is an issue that could be solved with new hardware (probably a DP adapter), due to the DP adapter you currently have seeming to not work properly, and VGA being a currently unfixable issue at the moment (I'll do some more research into this in the next couple of weeks, just to be sure). Sorry that I can't find a fix at the moment, again I'll do just a bit more research but I'm not sure if there is anything else that I could help with. Thanks for contributing to this issue though, and thanks for being cooperative throughout this issue!

**Comment by UHDbits** [comment] 2023-06-05 23:15
Hey @uberfunk, I just wanted to check if you had any answer to the above question? Just double checking so that this issue doesn't get marked as Stale until it's resolved. I'm still working on adding M83 Tiny support and documentation to the configuration, but it may be a bit delayed because I'm going to be dealing with the release of Sonoma.

**Comment by UHDbits** [comment] 2023-07-11 02:45
I have finally (seriously, finally) made the guide for M83 Tiny and M93p ThinkCentres! It's currently in the "sonoma" branch, but that branch will be merged into "main" in the next week or so. I want to thank everyone here for contributing to this issue. This issue will be closed, but if anyone here still needs some help, please feel free to reopen the issue!

**Closed by UHDbits** 2023-07-11 02:45 UTC
Labels: Documentation, Enhancement, Question
